### ISSUE TITLE
Version clash between pypi and github releases, both specify that latest version is 0.3.0 but release dates are very different

### ISSUE THREAD

**Issue by Skrethel** [thorwolpert/flask-jwt-oidc#13]
pypi: latest release [0.3.0](https://pypi.org/project/flask-jwt-oidc/#history) from **2021-02-17**
github: latest release [0.3.0](https://github.com/thorwolpert/flask-jwt-oidc/releases/tag/0.3.0) from **2024-03-04**

Also latest release on pypi is missing flask 3 support which is mentioned in changelog for 0.3.0 in github release.

Is it possible to release new version on pypi with flask 3 support?

**Comment by Skrethel** [comment]
I've noticed new versions on pypi - thank you very much for working on this.
Unfortunately new versions are not compatible with Flask 3 according to pypi's metadata
This what I can see in PKG file in 0.6.0 tar.gz
```
Requires-Dist: Flask (>=2,<3)
Requires-Dist: cachelib (>=0.13.0,<0.14.0)
Requires-Dist: python-jose (>=3.3.0,<4.0.0)
Requires-Dist: six (>=1.16.0,<2.0.0)
```

pip refuses to install both flask-jwt-oidc 0.6.0 and flask 3

```
pip install flask==3.0.3 flask-jwt-oidc==0.6.0
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install flask-jwt-oidc==0.6.0 and flask==3.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested flask==3.0.3
    flask-jwt-oidc 0.6.0 depends on Flask<3 and >=2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
The same error happens for 0.5.0.

This seems to be caused by poetry version spec used for Flask dependency: 
```
Flask = "^2"
```
According to poetry docs `^2` adds implicit `<3` limit
```
^1 	>=1.0.0 <2.0.0
```
Maybe Flask dep should be set to
```
Flask = ">=2"
```
to allow both 2 and 3 versions of Flask?

**Comment by thorwolpert** [comment]
Thanks, i'll try to get a new release out over the next couple of weeks tested in Flask3.
Appreciate the info shared here!

**Comment by thorwolpert** [comment]
Have a look, hopefully release 0.7 meets your needs.

**Comment by Skrethel** [comment]
0.7.0 installs nicely with Flask 3. Thank you very much for this release and sorry for delay in closing this.
